### ISSUE TITLE
Create and include Reflectoring logo

### ISSUE THREAD

**Issue by thombergs** [reflectoring/reflectoring.github.io#2]
The logo should be included
* in the header
* as favicon (http://realfavicongenerator.net/)

**Comment by thombergs** [comment]
![hipsterlogogenerator_1480620015367](https://cloud.githubusercontent.com/assets/1363578/20808785/2b213cfa-b804-11e6-94e4-9dac3ea34354.png)

**Comment by RudiKlassen** [comment]
![logo_v1](https://cloud.githubusercontent.com/assets/6597008/21890035/09a08b24-d8cc-11e6-9668-2a077a96499f.png)
