### ISSUE TITLE
blog layout for smartphones

### ISSUE THREAD

**Issue by matthiasbalke** [reflectoring/reflectoring.github.io#38]
After including the header logo the layout is broken on my iPhone 5s. We should check the layout working for commonly used smartphone resolutions. 

![img_6725](https://cloud.githubusercontent.com/assets/91990/22865172/a7bc52ac-f15e-11e6-9078-bbd4c0b18712.PNG)
![img_6726](https://cloud.githubusercontent.com/assets/91990/22865173/a7e8808e-f15e-11e6-9cfc-695b33e8c615.PNG)

**Comment by thombergs** [comment]
please check again with the new theme

**Comment by matthiasbalke** [comment]
it's a lot cleaner look now. issue closed!
