### ISSUE TITLE
Use a theme without teaser images for each post

### ISSUE THREAD

**Issue by thombergs** [reflectoring/reflectoring.github.io#75]
Having to find a teaser image for each blog post can be rather time consuming and in the end the freely available images don't look as good anyways. So, we should replace the Skinny Bones theme with a pleasing theme that doesn't need an image for each post, like this one: http://adventurethemes.com/demo/writer/jekyll/v1-d-20-2/

**Comment by matthiasbalke** [comment]
This theme uses a custom image for each post. What's the difference?

**Comment by thombergs** [comment]
But you could leave the image out and it would still look good :)

**Comment by matthiasbalke** [comment]
Ok I dind't try that. How about the banner

**Comment by thombergs** [comment]
closed. used minimal mistakes theme
